### ISSUE TITLE
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Blizzsuxx** [neuralchen/SimSwap#114]
after using

`python test_video_swapsingle.py --isTrain false --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/multi_people_1080p.mp4 --output_path ./output/multi_test_swapsingle.mp4 --temp_path ./temp_results`

it gives the following error 
```

Traceback (most recent call last):
  File "test_video_swapsingle.py", line 11, in <module>
    from insightface_func.face_detect_crop_single import Face_detect_crop
  File "/media/user/games/Stuff/SimSwap-main/insightface_func/face_detect_crop_single.py", line 8, in <module>
    from insightface.model_zoo import model_zoo
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/site-packages/insightface/__init__.py", line 8, in <module>
    import onnxruntime
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/site-packages/onnxruntime/__init__.py", line 34, in <module>
    raise import_capi_exception
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/site-packages/onnxruntime/capi/_pybind_state.py", line 11, in <module>
    from . import _ld_preload  # noqa: F401
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/site-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcudart = CDLL("libcudart.so.11.0", mode=RTLD_GLOBAL)
  File "/home/user/anaconda3/envs/simswap2/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

```

note that i did everything according to the "preparation" section, also the program worked before updating my graphics driver to 470 (Nvidia, Linux)

**Comment by Bob-jpg** [comment]
cuda版本的问题10.1试试
