### ISSUE TITLE
Stuck on "End"

### ISSUE THREAD

**Issue by st4tus** [neuralchen/SimSwap#120]
Last couple of lines of the logs below, no matter what configuration of arguments is used, it's stuck on End and it's not doing anything.

```
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: False
verbose: False
video_path: ./demo_file/multi_people_1080p.mp4
which_epoch: latest
-------------- End ----------------
```

**Comment by harlankolo** [comment]
Same problem here.

**Comment by bradteemo** [comment]
same problem, RTX 3070 laptop. Stuck on "END", not processing.  Any help plz?

**Comment by realies** [comment]
https://github.com/neuralchen/SimSwap/issues/71#issuecomment-920303689

**Comment by st4tus** [comment]
> [#71 (comment)](https://github.com/neuralchen/SimSwap/issues/71#issuecomment-920303689)

```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.1
```

**Comment by realies** [comment]
@st4tus, I've updated the comment.

**Comment by st4tus** [comment]
> @st4tus, I've updated the comment.

```
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::cudatoolkit-11.1.1-heb2d755_7'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-11.1.1-heb2d755_7
location of failed script: C:\ProgramData\Anaconda3\Scripts\.cudatoolkit-post-link.bat
==> script messages <==
"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

==> script output <==
stdout:
stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()
```

**Comment by st4tus** [comment]
> @st4tus, I've updated the comment.

and when running the first example command after your suggestion: python test_one_image.py --isTrain false --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path crop_224/6.jpg --pic_b_path crop_224/ds.jpg --output_path output/

```
Traceback (most recent call last):
  File "test_one_image.py", line 30, in <module>
    opt = TestOptions().parse()
  File "C:\users\status\desktop\pog\options\base_options.py", line 84, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\cuda\__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```

**Comment by st4tus** [comment]
I mean, can you just not create a GUI? I swear 98% of Github repositories never worked for me it's such a shame, you're wasting your potential...

**Comment by theghostlibrary** [comment]
Solved by dodo295 for me, thanks! (GTX 3070)

 https://github.com/neuralchen/SimSwap/issues/15#issuecomment-866039674
