### ISSUE TITLE
"./checkpoints\people\latest_net_G.pth not exists yet!" problem

### ISSUE THREAD

**Issue by craigfakeboss** [neuralchen/SimSwap#130]
Went through the installation process without a problem.  Try to test the first swap from demo directory to see how it works and got this message.

./checkpoints\people\latest_net_G.pth not exists yet!
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 40, in <module>
    model = create_model(opt)
  File "C:\SimSwap-main\models\models.py", line 18, in create_model
    model.initialize(opt)
  File "C:\SimSwap-main\models\fs_model.py", line 71, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)
  File "C:\SimSwap-main\models\base_model.py", line 58, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException

I have latest_net_G.pth in proper directory.  Did I miss a step in installation?

**Comment by Haris33-coder** [comment]
@swastikdeeplearning Solution worked for me as well. Thanks.

**Comment by sxf97** [comment]
There is such an error when running the code：“No such file or directory: 'models/BEST_checkpoint.tar'”，I did not find this file anywhere in the code！！！
![)A)UMO{F$8M@8D%H6U2OJDX](https://user-images.githubusercontent.com/74477028/141952871-31ec47e2-ca1c-4627-b088-02b19e41c7f7.png)
