### ISSUE TITLE
mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by f0restw0w** [neuralchen/SimSwap#153]
Traceback (most recent call last):
  File "test_one_image.py", line 57, in <module>
    latend_id = model.netArc(img_id_downsample)
  File "D:\Dev\Anaconda3\envs\simswap\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\project\ai\SimSwap\models\models.py", line 145, in forward
    x = self.fc(x)
  File "D:\Dev\Anaconda3\envs\simswap\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Dev\Anaconda3\envs\simswap\lib\site-packages\torch\nn\modules\linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Dev\Anaconda3\envs\simswap\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by Bob-jpg** [comment]
you can use test_whole_swapimage.py

**Comment by jz-exwzd** [comment]
It can be due to an error in the input size on the upstream of the netArc model, causing the matrix dimension mat1 and mat2 to be mismatched on the shown linear layer.
In this case, it can be that your "img_id_downsample" is not of correct shape. Make sure that it is of shape 112x112 (if I am not mistaken).
