### ISSUE TITLE
ORT help

### ISSUE THREAD

**Issue by NickNamePozi369** [neuralchen/SimSwap#196]
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 44, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "F:\Games\Q\SimSwap-main\insightface_func\face_detect_crop_single.py", line 32, in __init__
    model = model_zoo.get_model(onnx_file)
  File "F:\Games\Q\anac\envs\simswap\lib\site-packages\insightface\model_zoo\model_zoo.py", line 56, in get_model
    model = router.get_model()
  File "F:\Games\Q\anac\envs\simswap\lib\site-packages\insightface\model_zoo\model_zoo.py", line 23, in get_model
    session = onnxruntime.InferenceSession(self.onnx_file, None)
  File "F:\Games\Q\anac\envs\simswap\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\Games\Q\anac\envs\simswap\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 364, in _create_inference_session
    "onnxruntime.InferenceSession(..., providers={}, ...)".format(available_providers))
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by Fibonacci134** [comment]
You are definitely using onnxruntime-gpu 1.0.
Do this:
Pip uninstall onnxruntime-gpu=1.10


Pip install onnxruntime-gpu=1.9

The error should go away. For 1.10 you need to set certain variables such as your Cuda execution provider.

**Comment by NickNamePozi369** [comment]
> You are definitely using onnxruntime-gpu 1.0. Do this: Pip uninstall onnxruntime-gpu==1.10
> 
> Pip install onnxruntime-gpu==1.9
> 
> The error should go away. For 1.10 you need to set certain variables such as your Cuda execution provider

Yeah all work thank you!

**Comment by Fibonacci134** [comment]
Anytime :)
