### ISSUE TITLE
A lot of error, need help

### ISSUE THREAD

**Issue by HTNO** [neuralchen/SimSwap#209]
I'm very new for this.
I faced a lot of error code while using simswap.
What should I do with this error code to complete my simswap command.

Command :
python test_video_swapsingle.py --crop_size 224 --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/multi_people_1080p.mp4 --output_path ./output/multi_test_swapsingle.mp4 --temp_path ./temp_results

Result :
-------------- End ----------------
Traceback (most recent call last):
  File "test_video_swapmulti.py", line 55, in <module>
    model = create_model(opt)
  File "F:\Simswap\SimSwap-main\models\models.py", line 18, in create_model
    model.initialize(opt)
  File "F:\Simswap\SimSwap-main\models\fs_model.py", line 67, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "F:\Users\My_PC\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\Users\My_PC\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "F:\Users\My_PC\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 720, in persistent_load
    _check_container_source(*data)
  File "F:\Users\My_PC\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 639, in _check_container_source
    f.write(lines)
  File "F:\Users\My_PC\anaconda3\envs\simswap\lib\encodings\cp874.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 1153: character maps to <undefined>

Thanks a lot.

**Comment by Someonetoldme584** [comment]
Same problem

**Comment by LMaster321** [comment]
Same, pls help

**Comment by Locotar** [comment]
Same... help~
