### ISSUE TITLE
Video Creation Error: AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by mrcloudmist** [neuralchen/SimSwap#216]
I finished all the steps here https://www.youtube.com/watch?v=1NWJz_rFMq0 but it looks like this when compiling a video

(simswap) D:\IDM Downloads\Video\Simswap\SimSwap-main>python test_video_swapsingle.py --crop_size 224 --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/sss.png --video_path ./demo_file/1st.vlc --output_path ./output/1st.mp4 --temp_path ./temp_results
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 42, in <module>
    opt = TestOptions().parse()
  File "D:\IDM Downloads\Video\Simswap\SimSwap-main\options\base_options.py", line 84, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "D:\Anaconda\envs\simswap\lib\site-packages\torch\cuda\__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by sunderbharath85** [comment]
any update on this?
