### ISSUE TITLE
Error when trying to fine-tune model

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#229]
When i try to fine-tune published model "people" with VGGFACE2 dataset  (aligned and cropped with 256) i got this error - despite the fact that it looks like this file is still in the folder - `/SimSwap/checkpoints/people/latest_net_G.pth`

Full command that I used: 
`python -W ignore train.py --name people --gpu_ids 0 --continue_train True  --checkpoints_dir "./checkpoints" --load_pretrain "./checkpoints/people" --dataset "./vggface2_test_256_aligned" --train_simswap True --Gdeep False`
```
----------- Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
Gdeep: True
batchSize: 16
beta1: 0.0
checkpoints_dir: ./checkpoints
continue_train: True
dataset: /content/vggface2_test_256_aligned
gpu_ids: 0
isTrain: True
lambda_feat: 10.0
lambda_id: 30.0
lambda_rec: 10.0
load_pretrain: ./checkpoints/people
log_frep: 250
lr: 0.0004
model_freq: 100
name: people
niter: 10000
niter_decay: 10000
phase: train
sample_freq: 1000
tag: simswap
total_step: 1000000
train_simswap: True
which_epoch: latest
-------------- End ----------------
Resuming from epoch 519 at iteration 4062
GPU used :  0
Pretrained network G has fewer layers; The following are not initialized:
['down4', 'up4']
./checkpoints/people/latest_net_D.pth not exists yet!
./checkpoints/people/latest_optim_G.pth not exists yet!
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    model.initialize(opt)
  File "/content/SimSwap/models/projected_model.py", line 84, in initialize
    self.load_optim(self.optimizer_G, 'G', opt.which_epoch, pretrained_path)
  File "/content/SimSwap/models/base_model.py", line 112, in load_optim
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException
```

**Comment by FuckingAlgorithm** [comment]
Did you solve the problem?
