### ISSUE TITLE
Looks like problem with saving model did not fixed: if len(gpu_ids) and torch.cuda.is_available(): TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#232]
```
( step: 249, ) G_Loss: 4.009 G_ID: 0.975 G_Rec: 8.404 G_feat_match: 2.851 D_fake: 0.029 D_real: 0.011 D_loss: 0.040 
( step: 499, ) G_Loss: 4.282 G_ID: 0.930 G_Rec: 8.074 G_feat_match: 2.796 D_fake: 0.021 D_real: 0.007 D_loss: 0.028 
Save test data
saving the latest model (steps 500)
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    model.save(step+1)            
  File "/content/SimSwap/models/projected_model.py", line 95, in save
    self.save_network(self.netG, 'G', which_epoch)
  File "/content/SimSwap/models/base_model.py", line 59, in save_network
    if len(gpu_ids) and torch.cuda.is_available():
TypeError: object of type 'NoneType' has no len()
```

**Comment by neuralchen** [comment]
fixed
