### ISSUE TITLE
Cannot resume training my model with --continue_train True after stopping, error

### ISSUE THREAD

**Issue by netrunner-exe** [neuralchen/SimSwap#234]
Command that I used:
`python -W ignore train.py --name simswap_256_test --gpu_ids 0 --continue_train True --checkpoints_dir "./checkpoints"  --dataset "./vggface2_test_256_aligned" --train_simswap True --Gdeep False`

Always:
```
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    model.initialize(opt)
  File "/content/SimSwap/models/projected_model.py", line 84, in initialize
    self.load_optim(self.optimizer_G, 'G', opt.which_epoch, pretrained_path)
  File "/content/SimSwap/models/base_model.py", line 112, in load_optim
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException

```

**Comment by netrunner-exe** [comment]
Fixed
