### ISSUE TITLE
Pillow Version on Test Video Multi

### ISSUE THREAD

**Issue by noobieshehe** [neuralchen/SimSwap#263]
hey, on 3 days ago. iam didnt get issue , but after this day iam updating and get issue on pillow version. i got this message.

`
Traceback (most recent call last):
  File "workspace/SimSwapOld/test_video_swapmulti.py", line 16, in <module>
    from torchvision import transforms
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/srv/conda/envs/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/srv/conda/envs/lib/python3.9/site-packages/PIL/__init__.py)
`
iam newbie.
how to get this fix issue ? downgrade pillow or torch version. what version most stable ?
thanks

**Comment by Fibonacci134** [comment]
uninstall pillow and then reinstall.
conda uninstall pillow
conda install pillow

**Comment by noobieshehe** [comment]
> uninstall pillow and then reinstall. conda uninstall pillow conda install pillow
> 
> (also, i would suggest not using python 3.9. 3.6-3.8 work better)

still same, but i uninstall pillow and try to pillow<7 its fixed. i think all need newest updates lib for this project.
