### ISSUE TITLE
Error about mistake in code

### ISSUE THREAD

**Issue by ssbugman** [neuralchen/SimSwap#280]
Traceback (most recent call last):
  File "P:\SimSwapmain\test_one_image.py", line 30, in <module>
    opt = TestOptions().parse()
  File "P:\SimSwapmain\options\base_options.py", line 84, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Python310\lib\site-packages\torch\cuda\__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by BeaverInGreenland** [comment]
Which Pytorch version are you using ?

**Comment by ssbugman** [comment]
First I tried that in Preparations, then installed and got "GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation."
After that i tried new PyTorch version and getting this error.
