### ISSUE TITLE
Incompatible with new GPU

### ISSUE THREAD

**Issue by ssbugman** [neuralchen/SimSwap#281]
GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37

New version of pytorch reports about conflict and not installing.

**Comment by BeaverInGreenland** [comment]
Did you try to install this pytorch version https://pytorch.org/get-started/previous-versions/#v180 ?
```conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge```

**Comment by ssbugman** [comment]
Now removed anaconda and did clean install. Instead string from preparation used your command
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
Didn't step "(option): pip install onnxruntime-gpu"

C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. Tried to save a patch, but couldn't create a writable file DataParallel.patch. Make sure it doesn't exist and your working directory is writable.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "test_one_image.py", line 35, in <module>
    model = create_model(opt)
  File "P:\SimSwapmain\models\models.py", line 18, in create_model
    model.initialize(opt)
  File "P:\SimSwapmain\models\fs_model.py", line 67, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 720, in persistent_load
    _check_container_source(*data)
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 639, in _check_container_source
    f.write(lines)
  File "C:\ProgramData\Anaconda3\envs\simswap\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 1153: character maps to <undefined>

**Comment by ssbugman** [comment]
Added encoding="utf-8" to line 635 in serialization.py. Getting lot of warnings about changed file but at least model started to work.
