### ISSUE TITLE
unicode encode error

### ISSUE THREAD

**Issue by Parkolando** [neuralchen/SimSwap#288]
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 55, in <module>
    model = create_model(opt)
  File "F:\simswap\SimSwap-main\models\models.py", line 17, in create_model
    model.initialize(opt)
  File "F:\simswap\SimSwap-main\models\fs_model.py", line 67, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 720, in persistent_load
    _check_container_source(*data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 639, in _check_container_source
    f.write(lines)
UnicodeEncodeError: 'cp949' codec can't encode character '\xe0' in position 1153: illegal multibyte sequence

I tried to fix this problem but nothing worked. What should I do?

**Comment by nagibator-hero** [comment]
Same problem, steel seeking for help

**Comment by Locotar** [comment]
Same problem..
