### ISSUE TITLE
512 model error

### ISSUE THREAD

**Issue by brazilgithub** [neuralchen/SimSwap#308]
I'm trying to use the 512 model, but I can't complete the process. I have this error. Could anyone help? Thanks.

`Traceback (most recent call last):
  File "test_wholeimage_swap_multispecific.py", line 70, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "C:\SimSwap\insightface_func\face_detect_crop_multi.py", line 47, in __init__
    assert 'detection' in self.models
AssertionError`

![image](https://user-images.githubusercontent.com/61645540/181734969-4e1f591a-3cf5-4f28-8a12-ee123b62e51e.png)

**Comment by LAFLAMIE1024** [comment]
Go through the 'preparation' in README please

**Comment by Player-ghq** [comment]
the same issue
