### ISSUE TITLE
help with training

### ISSUE THREAD

**Issue by ggspike** [neuralchen/SimSwap#328]
hi all. I don't understand how model training works. 
following the instructions i use the command: "python train.py --name simswap224_test --gpu_ids 0 --batchSize 4 --dataset /content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep False"

but i get error:
processing Swapping dataset images...
Finished preprocessing the Swapping dataset, total dirs number: 0...
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    train_loader    = GetLoader(opt.dataset,opt.batchSize,8,1234)
  File "X:\games\SimSwap-main\data\data_loader_Swapping.py", line 119, in GetLoader
    drop_last=True,shuffle=True,num_workers=num_workers,pin_memory=True)
  File "C:\Users\Spike\anaconda3\envs\simswap\lib\site-packages\torch\utils\data\dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "C:\Users\Spike\anaconda3\envs\simswap\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

I assume that the program doesn't find pictures for training. where should I put them?

**Comment by lizian1611** [comment]
> 大家好。我不明白模型训练是如何工作的。 按照说明我使用命令：“python train.py --name simswap224_test --gpu_ids 0 --batchSize 4 --dataset /content/TrainingData/vggface2_crop_arcfacealign_224 --Gdeep False”
> 
> 但我收到错误： 处理交换数据集图像... 已完成交换数据集的预处理，总目录数：0... 回溯（最后一次调用）： 文件“train.py”，第 159 行，在 train_loader = GetLoader(opt .dataset,opt.batchSize,8,1234) 文件“X:\games\SimSwap-main\data\data_loader_Swapping.py”，第 119 行，在 GetLoader drop_last=True,shuffle=True,num_workers=num_workers,pin_memory=True) 文件“C:\Users\Spike\anaconda3\envs\simswap\lib\site-packages\torch\utils\data\dataloader.py”，第 266 行，**init** sampler = RandomSampler(dataset, generator=generator) # 类型：忽略 文件“C:\Users\Spike\anaconda3\envs\simswap\lib\site-packages\torch\utils\data\sampler.py”，第 104 行，在**init** "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0
> 
> 我假设该程序找不到用于训练的图片。我应该把它们放在哪里？

--dataset ./content/TrainingData/vggface2_crop_arcfacealign_224
