### ISSUE TITLE
AttributeError: 'SGD' object has no attribute 'defaults'

### ISSUE THREAD

**Issue by johnrom1243** [neuralchen/SimSwap#354]
Im getting this error as soon as i try to run it. 
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 54, in <module>
    model = create_model(opt)
  File "C:\simswap\SimSwap-main\models\models.py", line 18, in create_model
    model.initialize(opt)
  File "C:\simswap\SimSwap-main\models\fs_model.py", line 67, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "C:\Users\manef\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\manef\anaconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "C:\Users\manef\anaconda3\envs\simswap\lib\site-packages\torch\optim\sgd.py", line 112, in __setstate__
    super().__setstate__(state)
  File "C:\Users\manef\anaconda3\envs\simswap\lib\site-packages\torch\optim\optimizer.py", line 84, in __setstate__
    self.defaults.setdefault('differentiable', False)
AttributeError: 'SGD' object has no attribute 'defaults'

**Comment by UITTrinhQuangTruong** [comment]
You should try previous pytorch versions (< 1.13): 
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by pinkllamas** [comment]
Is there a way to update your Colab at [](https://colab.research.google.com/drive/1PJw8wFN-VItYGOmtAJfeWUeYBJ4lFl6j?usp=sharing) so that it will prevent this error? I'm happy to do it myself, but I'm not able to figure out how.

**Comment by pinkllamas** [comment]
> Work for me, try run this code : pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 -f https://download.pytorch.org/whl/torch_stable.html

After which existing code should I run it in the colab? After the first box? The second? The third?
