### ISSUE TITLE
issue facing on RTX 3060ti 

### ISSUE THREAD

**Issue by Gadgetonixx** [neuralchen/SimSwap#358]
I have done clean install many times with different torch version however always I run into the same issue.

Issue: stuck at end & when leave the console open for long, after around 15-20 minutes the video is rendered. However, there is a flashy box texture appearing on the face and no face swap is done.

I think the insightface is not working but not sure 100%, also after doing clean install with multiple torch version I have currently installed the default one mentioned in the preparation section.

Installation I have followed is as bellow ( default one mention in the post but i did not installed any optional stuff.  

conda create -n simswap python=3.6
conda activate simswap
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch
pip install insightface==0.2.1 onnxruntime moviepy

Error log : 

(simswap) D:\ALLAI\SimSwap-main\SimSwap-main>pip install insightface==0.2.1 onnxruntime moviepy
Collecting insightface==0.2.1
  Using cached insightface-0.2.1-py2.py3-none-any.whl (24 kB)
Collecting onnxruntime
  Using cached onnxruntime-1.10.0-cp36-cp36m-win_amd64.whl (5.2 MB)
Collecting moviepy
  Using cached moviepy-1.0.3-py3-none-any.whl
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp36-cp36m-win_amd64.whl (8.5 MB)
Collecting easydict
  Using cached easydict-1.10-py3-none-any.whl
Collecting scikit-image
  Using cached scikit_image-0.17.2-cp36-cp36m-win_amd64.whl (11.5 MB)
Requirement already satisfied: Pillow in c:\users\user\anaconda3\envs\simswap\lib\site-packages (from insightface==0.2.1) (8.3.1)
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp36-cp36m-win_amd64.whl (6.8 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting scipy
  Using cached scipy-1.5.4-cp36-cp36m-win_amd64.whl (31.2 MB)
Requirement already satisfied: numpy in c:\users\user\anaconda3\envs\simswap\lib\site-packages (from insightface==0.2.1) (1.19.2)
Collecting onnx
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\USER\anaconda3\envs\simswap\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-s5i0b0x5\\onnx_f27b707f6a564c8ca891ba82898c3ae5\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-s5i0b0x5\\onnx_f27b707f6a564c8ca891ba82898c3ae5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-a0o5qkiu'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-s5i0b0x5\onnx_f27b707f6a564c8ca891ba82898c3ae5\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-s5i0b0x5\onnx_f27b707f6a564c8ca891ba82898c3ae5\setup.py", line 81, in <module>
        assert CMAKE, "Could not find cmake executable!"
    AssertionError: Could not find cmake executable!

    ----------------------------------------

**Comment by Gadgetonixx** [comment]
I am able to resolve it using the details available on #197

used the below steps 

Preparation
__________________________________________________________________________________________________________________________________________________________________________________________________________________
conda create -n simswap python=3.6
conda activate simswap
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
(option): pip install --ignore-installed imageio
pip install insightface==0.2.1 onnxruntime moviepy
