### ISSUE TITLE
SIMSWAP is not installed. I don't understand what the problem is. Help me please

### ISSUE THREAD

**Issue by DamiSome** [neuralchen/SimSwap#415]
I'm getting to "pip install insightface==0.2.1 onnxruntime moviepy" and and I get errors.. Visual studio and build tools installed. Windows 10, gtx 1650, ryzen 7. Cuda 12.0. CPU version also give errors.

```
(simswap) C:\Windows\system32>pip install insightface==0.2.1 onnxruntime moviepy
Collecting insightface==0.2.1
  Using cached insightface-0.2.1-py2.py3-none-any.whl (24 kB)
Collecting onnxruntime
  Using cached onnxruntime-1.10.0-cp36-cp36m-win_amd64.whl (5.2 MB)
Collecting moviepy
  Using cached moviepy-1.0.3-py3-none-any.whl
Collecting opencv-python
  Using cached opencv-python-4.7.0.72.tar.gz (91.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scikit-image
  Using cached scikit_image-0.17.2-cp36-cp36m-win_amd64.whl (11.5 MB)
Collecting onnx
  Using cached onnx-1.14.0.tar.gz (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting easydict
  Using cached easydict-1.10-py3-none-any.whl
Collecting scipy
  Using cached scipy-1.5.4-cp36-cp36m-win_amd64.whl (31.2 MB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: Pillow in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from insightface==0.2.1) (8.4.0)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp36-cp36m-win_amd64.whl (8.5 MB)
Requirement already satisfied: numpy in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from insightface==0.2.1) (1.19.5)
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp36-cp36m-win_amd64.whl (6.8 MB)
Collecting flatbuffers
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting protobuf
  Using cached protobuf-3.19.6-cp36-cp36m-win_amd64.whl (897 kB)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from moviepy) (2.15.0)
Collecting imageio-ffmpeg>=0.2.0
  Using cached imageio_ffmpeg-0.4.8-py3-none-win_amd64.whl (22.6 MB)
Collecting proglog<=1.0.0
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting decorator<5.0,>=4.0.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from requests->insightface==0.2.1) (2021.5.30)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting colorama
  Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting importlib-resources
  Using cached importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp36-cp36m-win_amd64.whl (51 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: six>=1.5 in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from python-dateutil>=2.1->matplotlib->insightface==0.2.1) (1.16.0)
Collecting protobuf
  Using cached protobuf-4.21.0-py3-none-any.whl (291 kB)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\damir\anaconda3\envs\simswap\lib\site-packages (from onnx->insightface==0.2.1) (4.1.1)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp36-cp36m-win_amd64.whl (4.2 MB)
Collecting networkx>=2.0
  Using cached networkx-2.5.1-py3-none-any.whl (1.6 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2020.9.3-py3-none-any.whl (148 kB)
Collecting joblib>=0.11
  Using cached joblib-1.1.1-py2.py3-none-any.whl (309 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 4.21.0 at https://files.pythonhosted.org/packages/27/82/986065ef305c0989c99d8ef3f29e58a03fac6e64bb2c36ffe64500cc6955/protobuf-4.21.0-py3-none-any.whl#sha256=4e78116673ba04e01e563f6a9cca2c72db0be8a3e1629094816357e81cc39d36 (from https://pypi.org/simple/protobuf/))
Reason for being yanked: Required python version not configured correctly (https://github.com/protocolbuffers/protobuf/issues/10076)
Building wheels for collected packages: onnx, opencv-python
  Building wheel for onnx (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Damir\anaconda3\envs\simswap\python.exe' 'C:\Users\Damir\anaconda3\envs\simswap\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Damir\AppData\Local\Temp\tmpv612pe3n'
       cwd: C:\Users\Damir\AppData\Local\Temp\pip-install-ccq0woy2\onnx_6269004a454e4918b289571cbaa9c08d
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\Damir\\anaconda3\\envs\\simswap\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\Damir\\anaconda3\\envs\\simswap\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp36-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.6', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Damir\\AppData\\Local\\Temp\\pip-install-ccq0woy2\\onnx_6269004a454e4918b289571cbaa9c08d']
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:17 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
      metadata_directory)
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\setuptools\build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\setuptools\build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 365, in <module>
      "backend-test-tools = onnx.backend.test.cmd_tools:main",
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Damir\AppData\Local\Temp\pip-build-env-oek7t39a\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 236, in run
      self.run_command("cmake_build")
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 222, in run
      subprocess.check_call(cmake_args)
    File "C:\Users\Damir\anaconda3\envs\simswap\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\Damir\\anaconda3\\envs\\simswap\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\Damir\\anaconda3\\envs\\simswap\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp36-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.6', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Damir\\AppData\\Local\\Temp\\pip-install-ccq0woy2\\onnx_6269004a454e4918b289571cbaa9c08d']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Building wheel for opencv-python (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Damir\anaconda3\envs\simswap\python.exe' 'C:\Users\Damir\anaconda3\envs\simswap\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Damir\AppData\Local\Temp\tmpjgugd2wr'
       cwd: C:\Users\Damir\AppData\Local\Temp\pip-install-ccq0woy2\opencv-python_e2cc667883f849a29785c03696838cf9
  Complete output (323 lines):


  --------------------------------------------------------------------------------
  -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Visual Studio 17 2022 x64 v143' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Visual Studio 16 2019 x64 v142' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 16 2019

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Visual Studio 16 2019 x64 v142' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'Visual Studio 15 2017 x64 v141' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Visual Studio 15 2017 x64 v141' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  -- Configuring incomplete, errors occurred!
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.6 requires Microsoft Visual Studio 2022.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  Or with "Visual Studio 2019":

      https://visualstudio.microsoft.com/vs/

  Or with "Visual Studio 2022":

      https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for opencv-python
Failed to build onnx opencv-python
ERROR: Could not build wheels for onnx, opencv-python which use PEP 517 and cannot be installed directly
```

**Comment by WandererGuy** [comment]
you can try pip install onnx==1.4.1 before 
pip install insightface==0.2.1 onnxruntime moviepy
