### ISSUE TITLE
train error in colab 

### ISSUE THREAD

**Issue by desertzk** [neuralchen/SimSwap#416]
Traceback (most recent call last):
  File "/content/SimSwap/train.py", line 139, in <module>
    model.initialize(opt)
  File "/content/SimSwap/models/projected_model.py", line 49, in initialize
    self.netArc = netArc_checkpoint['model'].module
TypeError: 'ResNet' object is not subscriptable

**Comment by JulesLiu** [comment]
If I remember it correctly, I used the solution by the wonderful guy's in #404 , and solved.

**Comment by desertzk** [comment]
Thanks JulesLiu that works but the follow error comes
'EfficientNet' object has no attribute 'act1'
  File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 35, in _make_efficientnet
    pretrained.layer0 = nn.Sequential(model.conv_stem, model.bn1, model.act1, *model.blocks[0:2])
  File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 64, in _make_projector
    pretrained = _make_efficientnet(model)
  File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 108, in __init__
    self.pretrained, self.scratch = _make_projector(im_res=im_res, cout=self.cout, proj_type=self.proj_type, expand=self.expand)
  File "D:\pythonworkspace\SimSwap\pg_modules\projected_discriminator.py", line 161, in __init__
    self.feature_network = F_RandomProj(**backbone_kwargs)
  File "D:\pythonworkspace\SimSwap\models\projected_model.py", line 58, in initialize
    self.netD = ProjectedDiscriminator(diffaug=False, interp224=False, **{})
  File "D:\pythonworkspace\SimSwap\train.py", line 139, in <module>
    model.initialize(opt)
AttributeError: 'EfficientNet' object has no attribute 'act1'

I think maybe the model are changed.

**Comment by JulesLiu** [comment]
> Thanks JulesLiu that works but the follow error comes 'EfficientNet' object has no attribute 'act1' File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 35, in _make_efficientnet pretrained.layer0 = nn.Sequential(model.conv_stem, model.bn1, model.act1, *model.blocks[0:2]) File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 64, in _make_projector pretrained = _make_efficientnet(model) File "D:\pythonworkspace\SimSwap\pg_modules\projector.py", line 108, in **init** self.pretrained, self.scratch = _make_projector(im_res=im_res, cout=self.cout, proj_type=self.proj_type, expand=self.expand) File "D:\pythonworkspace\SimSwap\pg_modules\projected_discriminator.py", line 161, in **init** self.feature_network = F_RandomProj(**backbone_kwargs) File "D:\pythonworkspace\SimSwap\models\projected_model.py", line 58, in initialize self.netD = ProjectedDiscriminator(diffaug=False, interp224=False, **{}) File "D:\pythonworkspace\SimSwap\train.py", line 139, in model.initialize(opt) AttributeError: 'EfficientNet' object has no attribute 'act1'
> 
> I think maybe the model are changed.

With pleasure. And that's what happened to me, solved one error, then a new one, for now I'm stuck at no images were loaded/recognized. For this act1 error, you may check #307 .

**Comment by desertzk** [comment]
thanks for the help I solve it.but I don't encount no images load problem. the training start I think maybe you can check dataset path.

**Comment by MicheleDaVinci** [comment]
Hello there are problems with the training both locally and in colab, I hope it will be solved as soon as possible thanks in advance good work.

![Screenshot 2023-06-18](https://github.com/neuralchen/SimSwap/assets/136981250/7f346484-d9f8-4054-b561-18d07a740fb9)
