### ISSUE TITLE
Error:test_video_swapsingle.py

### ISSUE THREAD

**Issue by Solenyalyl** [neuralchen/SimSwap#457]
when I run 
python test_video_swapsingle.py --crop_size 224 --use_mask --name people --Arc_path ./arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/Iron_man.jpg --video_path ./demo_file/multi_people_1080p.mp4 --output_path ./output/multi_test_swapsingle.mp4 --temp_path ./temp_results

It returns:
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 86, in <module>
    no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask,crop_size=crop_size)
  File "/home/alien/simswap/SimSwap/util/videoswap.py", line 115, in video_swap
    clips = ImageSequenceClip(image_filenames,fps = fps)
  File "/home/alien/anaconda3/envs/simswap/lib/python3.6/site-packages/moviepy/video/io/ImageSequenceClip.py", line 64, in __init__
    if isinstance(sequence[0], str):
IndexError: list index out of range

is there anyone knows how to solve it? 
thanks

**Comment by Solenyalyl** [comment]
this is the opencv error
it doesnot deal the video well
you can solve it by "pip install opencv-contrib-python"
