### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by SeaCowTamer** [neuralchen/SimSwap#54]
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 34, in <module>
    opt = TestOptions().parse()
  File "C:\Program Files\SimSwap\SimSwap-main\options\base_options.py", line 84, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\[ME]\anaconda3\envs\simswap\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

How do I fix this, at first I thought I might have the wrong pytorch, but I downloaded it from simswap github https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/preparation.md

**Comment by PritomAhmed** [comment]
@SeaCowTamer  How did you solve this ?
