### ISSUE TITLE
FileNotFoundError when Face swapping for video preset

### ISSUE THREAD

**Issue by MarineBirch723** [neuralchen/SimSwap#67]
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 72, in <module>
    no_simswaplogo=opt.no_simswaplogo,use_mask=opt.use_mask)
  File "C:\Users\Szabolcs\Documents\SimSwap-main\util\videoswap.py", line 55, in video_swap
    net.load_state_dict(torch.load(save_pth))
  File "C:\Users\Szabolcs\.conda\envs\simswap\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Szabolcs\.conda\envs\simswap\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Szabolcs\.conda\envs\simswap\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './parsing_model/checkpoint\\79999_iter.pth'

**Comment by woctezuma** [comment]
#14, #62

**Comment by MarineBirch723** [comment]
This presents a new error

input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
Traceback (most recent call last):
  File "test_video_swapsingle.py", line 50, in <module>
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
TypeError: 'NoneType' object is not iterable

**Comment by woctezuma** [comment]
#39, #44, #46, #53, #66
