### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 1153: character maps to <undefined>

### ISSUE THREAD

**Issue by fortminors** [neuralchen/SimSwap#78]
Hello!

I am trying to run the demo after meeting all prerequisites, however after running the first command [here](https://github.com/neuralchen/SimSwap/blob/main/docs/guidance/usage.md): 

`python test_one_image.py --isTrain false --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path crop_224/6.jpg --pic_b_path crop_224/ds.jpg --output_path output/
`

I get the following error in my terminal:

```
------------ Options -------------
Arc_path: arcface_model/arcface_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: output/
phase: test
pic_a_path: crop_224/6.jpg
pic_b_path: crop_224/ds.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: False
verbose: False
video_path: ./demo_file/multi_people_1080p.mp4
which_epoch: latest
-------------- End ----------------
C:\Users\fortm\miniconda3\envs\simswap\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. Tried to save a patch, but couldn't create a writable file DataParallel.patch. Make sure it doesn't exist and your working directory is writable.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "test_one_image.py", line 36, in <module>
    model = create_model(opt)
  File "C:\Users\fortm\Desktop\SimSwap\models\models.py", line 18, in create_model
    model.initialize(opt)
  File "C:\Users\fortm\Desktop\SimSwap\models\fs_model.py", line 64, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "C:\Users\fortm\miniconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\fortm\miniconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "C:\Users\fortm\miniconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 720, in persistent_load
    _check_container_source(*data)
  File "C:\Users\fortm\miniconda3\envs\simswap\lib\site-packages\torch\serialization.py", line 639, in _check_container_source
    f.write(lines)
  File "C:\Users\fortm\miniconda3\envs\simswap\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 1153: character maps to <undefined>
```

Is there anything that I am doing wrong?

I am looking forward to any replies.

**Comment by woctezuma** [comment]
#24

**Comment by fortminors** [comment]
@woctezuma Thank you! That solved the problem, I just needed to set the utf-8 locale in windows settings
