### ISSUE TITLE
I feel that the processing speed is a little slow

### ISSUE THREAD

**Issue by wubangjunjava** [neuralchen/SimSwap#91]
I feel that the processing speed is a little slow. How can I improve it? It takes too long for a video to be processed.

**Comment by NNNNAI** [comment]
You can install the gpu version of onnx, the time to process a video will be greatly reduced. Using the command line below should be fine:
```
pip install onnxruntime-gpu==1.2.0
```
(Note: the version of onnxruntime-gpu may vary,which depend on you cuda version)

**Comment by wubangjunjava** [comment]
> You can install the gpu version of onnx, the time to process a video will be greatly reduced. Using the command line below should be fine:
> 
> ```
> pip install onnxruntime-gpu==1.2.0
> ```
> 
> (Note: the version of onnxruntime-gpu may vary,which depend on you cuda version)

thank you. Problem solving.

**Comment by ramnnv** [comment]
> 
> 
> You can install the gpu version of onnx, the time to process a video will be greatly reduced. Using the command line below should be fine:
> 
> ```
> pip install onnxruntime-gpu==1.2.0
> ```
> 
> (Note: the version of onnxruntime-gpu may vary,which depend on you cuda version)

Hi. My installation of SimSwap was doing great and working perfectly, but i update to onnxruntime and now im getting error and not working. May you help me to know what i doing wrong please, im newbie with all of this but i want to try that speed improvement. Thank you for all your work.

> C:\Users\ramnnv\anaconda3\envs\simswap\lib\site-packages\onnxruntime\capi\_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: No se puede encontrar el módulo especificado.'
>   warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
> Traceback (most recent call last):
>   File "C:\Users\ramnnv\anaconda3\envs\simswap\lib\site-packages\insightface\__init__.py", line 8, in <module>
>     import onnxruntime
>   File "C:\Users\ramnnv\anaconda3\envs\simswap\lib\site-packages\onnxruntime\__init__.py", line 12, in <module>
>     from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
> ImportError: cannot import name 'get_all_providers'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_video_swapsingle.py", line 11, in <module>
>     from insightface_func.face_detect_crop_single import Face_detect_crop
>   File "E:\SimSwap\SimSwap-main\insightface_func\face_detect_crop_single.py", line 8, in <module>
>     from insightface.model_zoo import model_zoo
>   File "C:\Users\ramnnv\anaconda3\envs\simswap\lib\site-packages\insightface\__init__.py", line 11, in <module>
>     "Unable to import dependency onnxruntime. "
> ImportError: Unable to import dependency onnxruntime.
>

**Comment by NNNNAI** [comment]
@ramnnv Did  you use this command line :***pip install onnxruntime-gpu==1.2.0*** to install onnx gpu? If so ,you can try to use older version of onnx gpu like 1.1.2 by using pip install onnxruntime-gpu==1.1.2

**Comment by ramnnv** [comment]
@NNNNAI yes, first i use 1.2.0, then i tried the old version you said (1.1.2), but still getting the same error. Now i back to the cpu onnx and SimSwap it's working again...

**Comment by NNNNAI** [comment]
@ramnnv which version of cuda did you use.You can type nvcc -V in your terminal to find out the cuda version

**Comment by ramnnv** [comment]
@NNNNAI CUDA Version: 11.2

**Comment by NNNNAI** [comment]
As shown in the offcial website of [onnx](https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#version-dependency),you could try to install  1.7.0 or 1.8.0
![image](https://user-images.githubusercontent.com/30747212/129693699-55eb1ede-8a97-4ae6-9859-bc79815cf7f3.png)

**Comment by ramnnv** [comment]
@NNNNAI I just tried 1.7.0 and 1.8.0 and got the same error, but thank you for trying to help me. In a few days i will reinstall windows, anaconda, gpu drivers, simswap... etc, so let's hope my problem can be solved.

**Comment by NNNNAI** [comment]
Hope you can solve the problem, have a nice day.
