### ISSUE TITLE
onnxruntime GPU - error

### ISSUE THREAD

**Issue by instant-high** [neuralchen/SimSwap#94]
After trying to 'upgrade' the old preparation to onnxruntime-gpu version SimSwap doesn't work anymore giving error 
_onnxruntime not found_ (sorry, didn't copy the whole error message)

I only did this:
pip install insightface==0.2.1 onnxruntime-gpu==1.2.0 moviepy

Fortunately I have external backups of my ENVS folder. So it was no big thing to get it back to work.

What can I do to make it work?

**Comment by mata3o** [comment]
Im curious about this as well. All i did was the following to upgrade to GPU:

conda activate simswap
pip install onnxruntime-gpu==1.2.0 

It did download and install correctly and after i closed and re-opened anaconda. If i was suppose to install anything else i didnt think i was suppose to and when i ran my test picture and video i got these messages: 

(simswap) C:\Users\user1\Desktop\Simswap\SimSwap-main>python test_video_swapsingle.py --isTrain false --use_mask --name people --Arc_path arcface_model/arcface_checkpoint.tar --pic_a_path ./demo_file/testpic.jpg --no_simswaplogo --video_path ./demo_file/testvid.mp4 --output_path ./output/testvid.mp4 --temp_path ./temp_results
C:\Users\user1\MiniConda3\envs\simswap\lib\site-packages\onnxruntime\capi\_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: The specified module could not be found.'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "C:\Users\user1\MiniConda3\envs\simswap\lib\site-packages\insightface\__init__.py", line 8, in <module>
    import onnxruntime
  File "C:\Users\user1\MiniConda3\envs\simswap\lib\site-packages\onnxruntime\__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
ImportError: cannot import name 'get_all_providers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_video_swapsingle.py", line 11, in <module>
    from insightface_func.face_detect_crop_single import Face_detect_crop
  File "C:\Users\user1\Desktop\Simswap Overlord\SimSwap-main\insightface_func\face_detect_crop_single.py", line 8, in <module>
    from insightface.model_zoo import model_zoo
  File "C:\Users\user1\MiniConda3\envs\simswap\lib\site-packages\insightface\__init__.py", line 11, in <module>
    "Unable to import dependency onnxruntime. "
ImportError: Unable to import dependency onnxruntime.


Any help would be greatly appreciated , cheers!

**Comment by ramnnv** [comment]
I'm asking the same on another thread. I got the same error when i change from CPU to GPU.

**Comment by NNNNAI** [comment]
Yep, it will be difficult to install onnxruntime-gpu version actually,  the specify version of onnxruntime maybe different depend on your machine and cuda version.Maybe you can check the list provided by onnx to find out the suitable version of onnx-gpu
![image](https://user-images.githubusercontent.com/30747212/129832722-b5eaaab2-abc9-4ddf-8fe1-78db8c1d5838.png)

**Comment by Maouniel** [comment]
Kinda same problem. 
My CUDA is 11.3, so i installed the latest ONNX version (1.8). Also tried 1.7. And then i see an error:
![image](https://user-images.githubusercontent.com/43824101/129846548-d5b476b2-81e9-4867-b117-f0bb5edcec1d.png)

**Comment by instant-high** [comment]
Just tried _pip install onnxruntime-gpu_ without explicit version number .
That installed onnxruntime 1.81
Seems to work so far, gives one error message (I didn't copy that message)

My CUDA version 11.2.135

Unfortunately no change in inference time ....  around 1.9 it/s for Video 1280x720

So I returned to previous installation.

Maybe I'll try a new separate SimSwap installation completly from the beginning, if that may change inference time??

**Comment by mata3o** [comment]
@Polukeev im a fellow 1070 user so ill have to do some toying with what you did this evening to check it out

@instant-high did changing to 256x256 degrade the outcome at all?

**Comment by instant-high** [comment]
@mata3o I mean if you have a small video containing only the face (maybe cut out before) or the face is small in the full frame decreased det-size mostly is working too. So of course don't resize the whole video to eg. 256

**Comment by instant-high** [comment]
I've tried on another computer, but not really satisfying result.

On the first one (GTX1050 / CUDA 11.2 / onnx-gpu 1.8.1) it get some error but it works, a bit slower than before, maybe fallback to cpu?
On the second one (GTX1060 / CUDA ?? / onnx-gpu 1.8.1) it seems to work without error but also no improvement.

Errormessage:
![onnxgpuerror](https://user-images.githubusercontent.com/77229558/130445311-d3e7c8c5-2a90-40d2-b793-7c56b4bf372c.jpg)

**Comment by Polukeev** [comment]
@instant-high did you try my solution? I don't have this message anymore "Failed to load library".
Run the command below and see will it help or no.
"pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html"
As i said new version of cuda (11 and above) needs newer version of cudatoolkit.

**Comment by instant-high** [comment]
@Polukeev Never change a running system..... even worse than before.
Nothing working, uninstalling onnx-gpu and installing onnx doesn't change the mess.
Gladly external backup of environment folder solved this problem quickly.

**Comment by Polukeev** [comment]
@instant-high sorry about it, just wanted to help. Strange but it helped me to remove all types of errors but i am still not sure is onnx-gpu running or just simple onnx since there is no drastic change in processing speed (something around 0.5-0.6 it/s).
"Never change a running system..... even worse than before" this is what i thought after installing onnxruntime-gpu for the first time. But without changes we will have the same results without improvements. I wish to see new version of this software where we will have possibility to have more source-face looking result.

**Comment by instant-high** [comment]
@Polukeev Everything is fine. After 30 years Windows and little bit programming I always use backups to avoid bigger trouble. Maybe Microsoft is invoved that's why it doesn' work as expected ;-)
